config/routes.rb
Rails.application.routes.draw do


  namespace :api do
    resources :products do
      collection do
        get :search
      end
    end
  end

  resources :news, only: :index

  resources :orders, only: :create do
    collection do
      get :receipt
    end
  end

  resources :checkout, only: [:index]

  resources :carts, only: [:index] do
    collection do
      get :info
      post :add
      post :remove
    end
  end

  match '/about', to: 'home#about', via: :get, as: :about

  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  root to: "products#home"

  get '/admin', to: 'admin/products#index'

  resources :products, only: [:index, :show] do
    collection do
      get 'autocomplete'
      get 'home'
      get 'search'
      get ':type', action: :index, constraints: {type: /#{Product::TYPES.map(&:pluralize).join('|')}/}, as: :type
    end
    resources :reviews, only: :create
  end
  resources :products, path: '/product', only: [:show]

  namespace :admin do
    resources :products do
      resources :reviews
    end
    resources :orders do
      member do
        post :fulfill
        post :cancel
      end
    end
    resources :bundles
    resources :news
  end
end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < Admin::AdminController

  def index
    @product = Product.find(params[:product_id])
    @reviews = @product.reviews
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to admin_product_reviews_path(product_id: params[:product_id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!

  def create
    product = Product.find(params[:product_id])
    product.reviews.create(review_params.merge(user: current_user))
    redirect_to product_path(product)
  end

  private
  def review_params
    params.require(:review).permit(:message, :rating)
  end
end

app/views/admin/reviews/index.html.erb
<ul class="nav nav-pills sub-nav">
  <li>
    <nav class="vendor-breadcrumb">
      <ol class="cd-breadcrumb narrow triangle custom-icons">
        <li class="home"><a href="<%= admin_products_path %>"><i class="fa fa-cubes" aria-hidden="true">&nbsp;</i> Products</a></li>
        <li class="current"><a href="javascript:;"><%= @product.title %></a></li>
      </ol>
    </nav>
  </li>
</ul>

<div class="form-container container">
  <div class="grid-card">
    <div class="actions">
      <ul class="tab-list">
        <li role="presentation">
          <%= link_to @product.title, admin_product_path(@product), class: 'tab' %>
        </li>
        <li role="presentation">
          <a class="tab active" href="javascript:;">Reviews</a>
        </li>
      </ul>
    </div>
  </div>
  <div class="form-content">
    <div class="row">
      <div class="col-md-12">
        <table class="table table-hover">
          <thead>
            <tr>
              <th></th>
              <th>Review</th>
              <th></th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @product.reviews.each do |review| %>
              <tr>
                <td>
                  <span data-rating="<%= review.rating %>" readonly></span>
                </td>
                <td>
                  <%= review.message %>
                </td>
                <td>
                  <%= link_to admin_product_review_path(review), method: :delete, class: 'danger', data: {confirm: 'Are you sure you want to delete review?'} do %>
                    <i class="fa fa-trash"></i>
                    Remove
                  <% end %>
                </td>
                <td></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>