config/routes.rb
Rails.application.routes.draw do


  namespace :api do
    resources :products do
      collection do
        get :search
      end
    end
  end

  resources :news, only: :index

  resources :orders, only: :create do
    collection do
      get :receipt
    end
  end

  resources :checkout, only: [:index]

  resources :carts, only: [:index] do
    collection do
      get :info
      post :add
      post :remove
    end
  end

  match '/about', to: 'home#about', via: :get, as: :about

  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  root to: "products#home"

  get '/admin', to: 'admin/products#index'

  resources :products, only: [:index, :show] do
    collection do
      get 'autocomplete'
      get 'home'
      get 'search'
      get ':type', action: :index, constraints: {type: /#{Product::TYPES.map(&:pluralize).join('|')}/}, as: :type
    end
    resources :reviews, only: :create
  end
  resources :products, path: '/product', only: [:show]

  namespace :admin do
    resources :products do
      resources :reviews
    end
    resources :orders do
      member do
        post :fulfill
        post :cancel
      end
    end
    resources :bundles
    resources :news
  end
end

app/models/order.rb
class Order < ApplicationRecord
  enum status: [:open, :fulfilled, :cancelled]

  # Relations
  belongs_to :user
  has_many :line_items
  has_one :billing_information
  has_one :shipping_information
  has_one :payment_information

  def total
    self.line_items.map(&:product).map(&:price).sum + self.shipping_cost
  end

  def fulfill
    self.fulfilled!
  end

  def cancel
    self.cancelled!
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::AdminController

  def index
    @orders = Order.page(params[:page])
  end

  def fulfill
    @order = Order.find(params[:id])
    @order.fulfill
    redirect_to admin_orders_path
  end

  def cancel
    @order = Order.find(params[:id])
    @order.cancel
    redirect_to admin_orders_path
  end

  def show
    @order = Order.find(params[:id])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!

  def create
    data = cart.data

    order = nil

    ActiveRecord::Base.transaction do
      order = current_user.orders.create!(order_params.merge({ total_price: data[:total] }))

      BillingInformation.create!(billing_params.merge(order: order))
      ShippingInformation.create!(shipping_params.merge(order: order)) unless order.ship_to_same_address
      PaymentInformation.create!(payment_params.merge(order: order))

      data[:items].each do |item|
        order.line_items.create!(product_id: item[:id], quantity: item[:count])
      end
    end

    # Send email with receipt to user
    UserMailer.receipt_summary(order).deliver_now if order && order.persisted?

    session[:cart] = {}  # Clear shopping cart

    render json: [], status: 200
  end

  def receipt
    @order = Order.includes(:line_items).last
    redirect_to root_path and return unless @order
  end

  private
  def cart
    @cart ||= Cart.new(session[:cart])
  end

  def order_params
    params.require(:order).permit(:shipping_cost, :shipping_method, :ship_to_same_address)
  end

  def billing_params
    params.require(:order).require(:billing_information).permit(:first_name, :last_name, :email, :phone, :address, :city, :postal_code, :country)
  end

  def shipping_params
    params.require(:order).require(:shipping_information).permit(:first_name, :last_name, :phone, :address, :city, :postal_code, :country)
  end

  def payment_params
    params.require(:order).require(:payment_information).permit(:first_name, :last_name, :account_number, :cvv, :expiration_date_month, :expiration_date_year)
  end
end

app/views/admin/orders/index.html.erb
<ul class="nav nav-pills sub-nav">
  <li>
    <nav class="vendor-breadcrumb">
      <ol class="cd-breadcrumb narrow triangle custom-icons">
        <li class="home"><a href="<%= admin_orders_path %>"><i class="fa fa-cubes" aria-hidden="true">&nbsp;</i> Orders</a></li>
      </ol>
    </nav>
  </li>
</ul>

<div>
  <div class="grid-container container">
    <div class="grid-card">
      <div class="actions">
        <ul class="tab-list">
          <li role="presentation">
            <a class="tab active" href="/admin/orders">All Orders</a>
          </li>
        </ul>
      </div>
      <div class="grid-content">
        <% if @orders.count == 0 %>
          <div class="row">
            <div class="col-md-offset-4 col-md-4 empty-placeholder">
              There are no orders in shop.
            </div>
          </div>
        <% else %>
          <table class="table table-stripped table-hover">
            <thead>
              <tr>
                <th></th>
                <th>Order Number</th>
                <th>Total Price</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <% @orders.each do |order| %>
                <tr>
                  <td></td>
                  <td>
                    <%= link_to admin_order_path(order) do %>
                      #<%= order.id %>
                    <% end %>
                  </td>
                  <td>
                    $<%= order.total.round(2) %>
                  </td>
                  <td>
                    <% if order.open? %>
                      <%= link_to fulfill_admin_order_path(order), method: :post, class: 'btn btn-success' do %>
                        <i class="fa fa-check"></i>
                        Fulfill
                      <% end %>
                      <%= link_to cancel_admin_order_path(order), method: :post, class: 'btn btn-danger' do %>
                        <i class="fa fa-check"></i>
                        Cancel
                      <% end %>
                    <% elsif order.fulfilled? %>
                      <button type="button" class="btn btn-sm btn-success" disabled><i class="fa fa-check" aria-hidden="true"></i> Fulfilled</button>
                    <% elsif order.cancelled? %>
                      <button type="button" class="btn btn-sm btn-danger" disabled><i class="fa fa-check" aria-hidden="true"></i> Cancelled</button>
                    <% end %>
                  </td>
                  <td></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<ul class="nav nav-pills sub-nav">
  <li>
    <nav class="vendor-breadcrumb">
      <ol class="cd-breadcrumb narrow triangle custom-icons">
        <li class="home"><a href="<%= admin_orders_path %>"><i class="fa fa-shopping-cart" aria-hidden="true">&nbsp;</i> Orders</a></li>
        <li class="current"><a href="javascript:;">Order #<%= @order.id %></a></li>
      </ol>
    </nav>
  </li>
</ul>

<div>
  <div class="grid-container container">
    <div class="grid-card">
      <div class="actions">
        <ul class="tab-list">
          <li role="presentation">
            <a class="tab active" href="javascript:;">Order #<%= @order.id %></a>
          </li>
        </ul>
      </div>
      <div class="grid-content">
        <section id="receipt" class="page-section row">
          <div class="col-md-12 col-lg-9">
            <div id="cart-content">
              <div class="cart-labels cart-item row hidden-xs">
                <div class="col-sm-4 col-sm-offset-2 ">
                  Item
                </div>
                <div class="col-sm-2">
                  Quantity
                </div>
                <div class="col-sm-2">
                  Discount
                </div>
                <div class="col-sm-2">
                  Item Total
                </div>
              </div>
              <% @order.line_items.each do |line_item|%>
                <div class="cart-item row">
                  <div class="col-xs-12 col-sm-2">
                    <div class="product-thumb">
                      <img class="img-responsive" alt="" src=<%=line_item.product.image_url%> >
                    </div>
                  </div>
                  <div class="col-xs-12 col-sm-4 cart-details">
                    <div class="h4 product-title">
                      <a href="javascript:;"><%=line_item.product.title%></a>
                      <small class="unit-price">
                      $<%=line_item.product.price%>
                      </small>
                    </div>
                  </div>
                  <div class="col-xs-12 col-sm-2 no-edit">
                    <div class="h3 quantity">
                      <%=line_item.quantity%>
                    </div>
                  </div>
                  <div class="col-xs-12 col-sm-2 cart-details no-edit">
                    <div class="h6 quantity">
                      $0.00
                    </div>
                  </div>
                  <div class="col-xs-12 col-sm-2 cart-details">
                    <div class="h4 total-price">
                      $<%=line_item.product.price%>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
          <div class="col-md-12 col-lg-3">
            <table class="table table-bordered">
              <tbody>
                <tr>
                  <td>Order number:</td>
                  <td>#<%=@order.id%></td>
                </tr>
                <tr>
                  <td>Shipping method:</td>
                  <td><%=@order.shipping_method%></td>
                </tr>
                <tr>
                  <td>Order Date:</td>
                  <td><%=@order.created_at.strftime("%b #{@order.created_at.day.ordinalize}, %Y")%> </td>
                </tr>
              </tbody>
            </table>
            <ul class="price-list list-group">
              <li class="list-group-item"><strong>Discount applied:</strong> <i class="badge">$0.00</i></li>
              <li class="list-group-item"><strong>Subtotal:</strong> <i class="badge"> $<%=@order.total_price%></i></li>
              <li class="list-group-item"><strong>Sales Tax:</strong> <i class="badge">$0.00</i></li>
              <li class="list-group-item"><strong>Shipping:</strong> <i class="badge">$<%=@order.shipping_cost%></i></li>
              <li class="list-group-item order-total h4 clearfix"><strong>Total:</strong>  <i class="badge"><%=@order.total_price + @order.shipping_cost%></i></li>
            </ul>
            <% if @order.open? %>
              <%= link_to fulfill_admin_order_path(@order), method: :post, class: 'btn btn-success' do %>
                <i class="fa fa-check"></i>
                Fulfill
              <% end %>
              <%= link_to cancel_admin_order_path(@order), method: :post, class: 'btn btn-danger' do %>
                <i class="fa fa-check"></i>
                Cancel
              <% end %>
            <% elsif @order.fulfilled? %>
              <button type="button" class="btn btn-sm btn-success" disabled><i class="fa fa-check" aria-hidden="true"></i> Fulfilled</button>
            <% elsif @order.cancelled? %>
              <button type="button" class="btn btn-sm btn-danger" disabled><i class="fa fa-check" aria-hidden="true"></i> Cancelled</button>
            <% end %>
          </div>
        </section>
      </div>
    </div>
  </div>
</div>