config/routes.rb
Rails.application.routes.draw do


  namespace :api do
    resources :products do
      collection do
        get :search
      end
    end
  end

  resources :news, only: :index

  resources :orders, only: :create do
    collection do
      get :receipt
    end
  end

  resources :checkout, only: [:index]

  resources :carts, only: [:index] do
    collection do
      get :info
      post :add
      post :remove
    end
  end

  match '/about', to: 'home#about', via: :get, as: :about

  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  root to: "products#home"

  get '/admin', to: 'admin/products#index'

  resources :products, only: [:index, :show] do
    collection do
      get 'autocomplete'
      get 'home'
      get 'search'
      get ':type', action: :index, constraints: {type: /#{Product::TYPES.map(&:pluralize).join('|')}/}, as: :type
    end
    resources :reviews, only: :create
  end
  resources :products, path: '/product', only: [:show]

  namespace :admin do
    resources :products do
      resources :reviews
    end
    resources :orders do
      member do
        post :fulfill
        post :cancel
      end
    end
    resources :bundles
    resources :news
  end
end

app/models/product.rb
class Product < ApplicationRecord
  include PgSearch

  mount_uploader :image, ::ImageUploader
  pg_search_scope :search_by_title, against: [:title],
    using: {
      tsearch: {
        prefix: true
      }
    }

  TYPES = %w(music film game)
  # Relations
  has_many :bundle_products
  has_many :bundles, through: :bundle_products
  has_many :reviews do
    def average_rating
      average(:rating).to_f
    end
  end

  # Validations
  validates :price, presence: true

  # Scopes
  scope :featured, ->{ where(featured: true) }
  scope :search, ->(keyward){ where("title ilike ?", "%#{keyward}%") }
  scope :by_category, -> (category) { where(category: category) }

  def image_url
    image.url if image
  end

  def as_json(options = nil)
    {
      id: self.id,
      type: self.type,
      title: self.title,
      price: self.price,
      image_url: self.image.thumb.url,
      reviews_average: self.reviews.average_rating
    }
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::AdminController
  before_action :constrain_type
  before_action :require_type, only: [:new, :create]
  before_action :load_class, only: [:index, :new, :create]

  def index
    @products = @klass.page(params[:page])
    if params[:category]
      @products = @products.by_category(params[:category])
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = @klass.new
  end

  def create
    @product = @klass.new product_params
    if @product.save
      redirect_to admin_products_path
    else
      render :new
    end
  end

  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(product_params)
      redirect_to admin_product_path(@product)
    else
      render :show
    end
  end

  protected
  def load_class
    @klass = params[:type].singularize.classify.constantize rescue Product
  end

  def product_params
    case params[:type]
    when 'film'
      film_params
    when 'music'
      music_params
    when 'game'
      game_params
    end
  end

  def film_params
    params.require(:film).permit(:title, :description, :category, :price, :duration, :number_of_discs, :format, :image)
  end

  def music_params
    params.require(:film).permit(:title, :description, :category, :price, :format, :released_at, :image)
  end

  def game_params
    params.require(:film).permit(:title, :description, :category, :price, :released_at, :image)
  end

  def constrain_type
    head(:bad_request) if params[:type].present? && !(params[:type] =~ /^(#{Product::TYPES.join('|')})$/)
  end

  def require_type
    head(:bad_request) if !params[:type].present?
  end
end

app/controllers/api/products_controller.rb
class Api::ProductsController < ApplicationController

  def search
    query = params[:q]
    render json: Product.search_by_title(query).limit(10)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :load_class

  def home
    @products = Product.featured.take(3)
    @featured = @products.any?

    unless @featured
      @products = Product.take(3)
    end
  end

  def autocomplete
    products = Product.search_by_title(params[:term]).with_pg_search_highlight
    render json: products.map {|p| { id: p.id, title: p.title, image_url: p.image_url, price: p.price } }, status: 200
  end

  def index
    @products = @klass.page(params[:page]).per(6)
    if @category = params[:category]
      @products = @products.by_category(@category)
    end
    @categories = @klass.categories.keys
    @products_categories_count = @klass.group(:category).count
    @type = params[:type]
  end

  def show
    @product = Product.find params[:id]
    @reviews = @product.reviews.includes(:user)
    @reviews_rating = @reviews.average_rating

    @review = @product.reviews.new if current_user
  end

  def search
    @search = params[:keyward]
    @products = Product.search(@search)
  end

  protected
  def load_class
    @klass = params[:type].singularize.classify.constantize rescue Product
  end
end

app/views/products/_product.html.erb
<div class="col-md-4 product-holder">
   <form class="custom" onsubmit="return false" method="post">
      <div class="product-item text-center">
         <a class="product-img" href=<%=product_path(product)%> >
         <img class="img-responsive" src=<%= product.image_url %> alt="Product Image">
         </a>
         <h3 class="product-title">
            <a href=<%=product_path(product)%> > <%= product.title %> </a>
            <span data-rating="<%= product.reviews.average_rating %>" style="margin: 4px auto;"></span>
         </h3>
         <div class="h4 product-price">
            <span>$<%= product.price %> </span>
         </div>
         <div class="buttons-holder">
            <button class="btn btn-danger btn-add-cart" data-productid=<%=product.id%> >Add to Cart</button>
         </div>
      </div>
   </form>
</div>

app/views/products/home.html.erb
<div id="home-banner" class="row">
 <!-- main slider -->
  <div id="home-carousel" class="carousel slide" data-ride="carousel">
     <!-- Indicators -->
     <ol class="carousel-indicators">
        <li data-target="#home-carousel" data-slide-to="0" class=""></li>
        <li data-target="#home-carousel" data-slide-to="1" class="active"></li>
     </ol>
     <!-- Wrapper for slides -->
     <div class="carousel-inner">
        <div class="item">
           <img src=<%=asset_path("fifa2.png")%> alt="demo_slide_2" style="height:430px">
           <div class="jumbotron carousel-caption">
              <h1><i class="fa fa-cube"></i> Fifa 2018</h1>
              <p>Get latest games for the year!</p>
              <p><a href=<%=root_path%> class="btn btn-primary btn-lg" role="button">Learn More<i class="fa fa-angle-double-right" aria-hidden="true"></i></a>
              </p>
           </div>
        </div>
        <div class="item active">
           <img src=<%=asset_path("heros2.png")%> alt="demo_slide_1" style="height:430px;margin-left: 50%;">
           <div class="jumbotron carousel-caption left">
              <h1>Movies</h1>
              <p>Heros all are here. Awesome.</p>
              <p><a href=<%=root_path%> class="btn btn-primary btn-lg" role="button">Shop Now <i class="fa fa-angle-double-right" aria-hidden="true"></i></a>
              </p>
           </div>
        </div>
     </div>
     <!-- Controls -->
     <a class="left carousel-control" href="#home-carousel" data-slide="prev">
     <i class="fa fa-angle-left"></i>
     </a>
     <a class="right carousel-control" href="#home-carousel" data-slide="next">
     <i class="fa fa-angle-right"></i>
     </a>
  </div>
  <!-- End main slider -->
</div>

 <section id="featured-products" class="page-section row">

    <h2 class="section-title"><span> <%=@featured ? "Featured" : "Latest" %> Products</span></h2>
    <!--item product  -->
    <% @products.each do |product| %>
      <%= render 'product', product: product %>
    <% end %>
 </section>

app/views/products/index.html.erb
<div id="banner" class="jumbotron row">
   <h1>All <%=@type.capitalize%></h1>
</div>
<section id="shop" class="page-section row">
   <div class="col-xs-12 col-sm-3">
      <div class="sidebar">
         <h4>Categories</h4>
         <ul class="list-unstyled  categories-group ">
            <%@categories.each do |category|%>
               <li>
                  <a href=<%=type_products_path(@type, category: category)%> class=<%="active" if @category == category %>><span class="badge"><%=@products_categories_count[category] || 0 %></span><%=category%></a>
               </li>
            <%end%>
         </ul>
      </div>
   </div>
   <div class="col-xs-12 col-sm-9">
      <div id="product-list">
         <div class="product-grid">
            <div id="" class="row" style="position: relative; height: 372.109px;">
               <% @products.each do |product| %>
                  <%= render 'product', product: product%>
               <% end %>
               <%if @products.count == 0%>
                  <h2 class="no-items"> No products found! </h2>
               <%end%>
            </div>
         </div>
      </div>
   </div>
   <div class="col-xs-12 col-sm-12">
      <%= paginate @products %>
   </div>
</section>

app/views/products/search.html.erb
<div id="banner" class="jumbotron row">
  <h1>Search Results</h1>
  <p class="found"> <%=@products.count%> Products Found</p>
</div>
<section id="shop" class="page-section row">
  <div class="col-xs-12 col-sm-12">
    <div class="product-grid">
      <div id="" class="row" style="position: relative; height: 0px;">
        <div class="col-xs-12">
          <% @products.each do |product| %>
            <%= render 'product', product: product%>
          <% end %>
          <%if @products.count == 0%>
            <h2 class="empty no-items">Sorry, there are no products matching your request.</h2>
          <%end%>

        </div>
      </div>
    </div>
    <div class="pagination-holder">
    </div>
  </div>
</section>

app/views/products/show.html.erb
<% content_for :head do %>
  <meta property="og:url"           content="<%=Rails.configuration.app_domain%><%=product_path(@product)%>" />
  <meta property="og:type"          content="<%=@product.class%>" />
  <meta property="og:title"         content="<%=@product.title%>" />
  <meta property="og:description"   content="<%=@product.description%>" />
  <meta property="og:image"         content="<%=Rails.configuration.app_domain%><%=@product.image%>" />
<% end %>

<div itemscope="" itemtype="http://schema.org/Product">
  <div id="banner" class="jumbotron row">
    <h1 itemprop="name"><%=@product.title%></h1>
    <p itemprop="description"><%=@product.description%></p>
  </div>
  <section id="single-product" class="page-section">

    <ol class="breadcrumb">
      <li class="hidden-xs"><a href=<%=root_path%> >Home</a></li>
      <li class="hidden-xs"><a href=<%=type_products_path(nav_name_for(@product))%> > <%=nav_name_for(@product)%> </a></li>
      <li class="active"><a href="javascript:;" class="no-click"> <%=@product.title%> </a></li>
    </ol>

    <form class="custom" onsubmit="return false" method="post" action="javascript:;">
      <div class="row">
        <div id="product-images">
          <div class="col-xs-12 col-sm-6">
            <img src= <%=@product.image_url %> class="zoomImg" >
          </div>
        </div>

        <div id="product-page">
          <div class="col-sm-6">
            <div class="price">
              <h2 itemprop="price">
                $<%=@product.price%>
              </h2>
            </div>
            <%if @product.reviews.count > 0%>
              <div class="row">
                <div class="col-md-6 col-sm-6 col-xs-6">
                  <h6> Users rate this product</h6>
                </div>
                <div class="col-md-6 col-sm-6 col-xs-6">
                  <span data-rating=<%=@product.reviews.average_rating%> readonly data-rateyo-rated-fill="#0c4d6c"></span>
                </div>
              </div>
            <%end%>

            <div class="excerpt" itemprop="description">
              <p><%=@product.description%></p>
            </div>

            <input type="hidden" name="productId" value="6">
            <div class="add-cart-holder form-group">
              <div class="quantity-selector">
                <button class="quantity-btn minus btn btn-lg btn-default"><i class="fa fa-minus"></i></button>
                <input class="form-control quantity" type="text" value="1" name="quantity">
                <button class="quantity-btn plus btn btn-lg btn-default"><i class="fa fa-plus"></i></button>
              </div>
              <a class="btn btn-lg btn-danger btn-add-cart js-with-count" data-productid=<%=@product.id%> href="javascript:;">Add to Cart <i class="fa fa-shopping-cart"></i></a>
            </div>

            <div id="sharrre" class="social-buttons">
              <h6 class="share-title">share with your friends</h6>

              <div class="fb-share-button"
                data-href="<%=Rails.configuration.app_domain%><%=product_path(@product)%>"
                data-layout="button"
                data-size="small"
                data-mobile-iframe="true">
                <a class="fb-xfbml-parse-ignore"
                    target="_blank"
                    href="https://www.facebook.com/sharer/sharer.php?u=<%=Rails.configuration.app_domain%><%=product_path(@product)%>&amp;src=sdkpreparse">Share</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </form>

    <!-- review -->
    <div  class="review-box row">
      <%if current_user%>
        <%= form_for(@review, url: product_reviews_path(@product), html: { method: :post, role: 'form' }) do |f| %>
          <div class="container">
            <div class="col-md-9 col-sm-9 col-xs-9">
              <%= f.text_area :message, placeholder: "Your review", class: "form-control", rows: 2 %>
            </div>
            <div class="col-md-3 col-sm-3 col-xs-3 text-center">
              <button type="submit" class="btn btn-primary btn-lg btn-block">Add Review!</button>
              <div class="stars" data-rating="0" data-rateyo-rated-fill="#0c4d6c"></div>
              <%= f.hidden_field :rating%>
            </div>
          </div>
        <% end %>
      <% end %>

      <h1 class="review-header text-center" >REVIEWS</h1>

      <div class="list-group">
        <!-- item  -->
        <%@reviews.each do |review|%>
          <a href="javascript:;" class="list-group-item">
            <div class="container">
              <div class="media col-md-2 col-sm-2 col-xs-2">
                <figure >
                <p class="text-bold"><i class="color-review fa fa-user" aria-hidden="true"></i> <%=review.user.name%> </p>
                <p class="text-bold"><i class="color-review fa fa-clock-o" aria-hidden="true"></i> <%=review_time(review)%> </p>
                <p class="text-bold"><i  class="color-review fa fa-calendar-o" aria-hidden="true"></i> <%=review_date(review)%></p>
                </figure>
              </div>
              <div class="col-md-7 col-sm-7 col-xs-7">
                <p class="list-group-item-text"> <%=review.message%> </p>
              </div>
              <div class="col-md-3 col-sm-3 col-xs-3 text-center">
                <span data-rating=<%= review.rating %> readonly data-rateyo-rated-fill="#0c4d6c"></span>
              </div>
            </div>
          </a>
        <%end%>

        <% if @reviews.count == 0 %>
          <h3 class="no-items"> No reivews yet, be ths first to review this product. </h3>
        <%end%>

      </div>
    </div>
    <!-- end review  -->

  </section>
</div>