config/routes.rb
Rails.application.routes.draw do


  namespace :api do
    resources :products do
      collection do
        get :search
      end
    end
  end

  resources :news, only: :index

  resources :orders, only: :create do
    collection do
      get :receipt
    end
  end

  resources :checkout, only: [:index]

  resources :carts, only: [:index] do
    collection do
      get :info
      post :add
      post :remove
    end
  end

  match '/about', to: 'home#about', via: :get, as: :about

  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  root to: "products#home"

  get '/admin', to: 'admin/products#index'

  resources :products, only: [:index, :show] do
    collection do
      get 'autocomplete'
      get 'home'
      get 'search'
      get ':type', action: :index, constraints: {type: /#{Product::TYPES.map(&:pluralize).join('|')}/}, as: :type
    end
    resources :reviews, only: :create
  end
  resources :products, path: '/product', only: [:show]

  namespace :admin do
    resources :products do
      resources :reviews
    end
    resources :orders do
      member do
        post :fulfill
        post :cancel
      end
    end
    resources :bundles
    resources :news
  end
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">
        <i class="fa fa-cube" aria-hidden="true"></i>
        <span>Ent-Me</span>
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="<%= 'active' if controller?('products', 'sells') %>">
          <%= link_to admin_products_path do %>
            <i class="fa fa-cubes" aria-hidden="true">&nbsp;</i>
            Products
          <% end %>
        </li>
        <li class="<%= 'active' if controller?('orders') %>">
          <%= link_to admin_orders_path do %>
            <i class="fa fa-cart-plus" aria-hidden="true">&nbsp;</i>
            Orders
          <% end %>
        </li>
        <div class="clearfix"></div>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? && current_user.admin? %>
          <li class="login-info">
            <div class="login-details">
              Logged in as
              <%= link_to current_user.name, "javascript:;" %>
              (admin)
            </div>
          </li>
          <li class="logout">
            <%= link_to destroy_user_session_path, method: :delete do %>
              <i class="fa fa-power-off" aria-hidden="true">&nbsp;</i>
              Logout
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to "Admin Login", "#"%>
          </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/admin_application.html.erb
<!DOCTYPE html>
<html lang="en">
   <head>
      <title>EntMe Admin</title>
      <%= csrf_meta_tags %>
      <%= stylesheet_link_tag    'admin_application', media: 'all' %>
      <%= javascript_include_tag 'application' %>
      <script src="https://cloud.tinymce.com/stable/tinymce.min.js?apiKey=9t97wiw90jsjehcw07r2e5mz6yt8o6cbrebxrafbbpj5qhi8"></script>
   </head>
   <body cz-shortcut-listen="true" class="admin">
      <%= render "layouts/header" %>
      <%= flash_messages %>
      <div class="container-fluid">
        <div class="row">
          <div class="col-sm-3 col-lg-2">
            <nav class="navbar navbar-default navbar-fixed-side">
              <div class="container">
                <div class="navbar-header">
                  <button class="navbar-toggle" data-target=".navbar-collapse" data-toggle="collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                  </button>
                </div>
                <div class="navbar-collapse collapse" aria-expanded="false" style="height: 1px;">
                  <ul class="nav navbar-nav">
                    <li class="<%= 'active' if controller?('admin/news') %>">
                      <a href="/admin/news"><i class="fa fa-newspaper-o" aria-hidden="true">&nbsp;</i> News</a>
                      <ul class="dropdown-menu">
                        <li>
                          <a href="<%= new_admin_news_path %>"><i class="fa fa-plus" aria-hidden="true">&nbsp;</i> Add News</a>
                        </li>
                      </ul>
                    </li>
                    <li class="<%= 'active' if controller?('admin/orders') %>">
                      <a href="/admin/orders"><i class="fa fa-shopping-bag" aria-hidden="true">&nbsp;</i> Orders</a>
                    </li>
                    <li class="<%= 'active' if controller?('admin/bundles') %>">
                      <a href="/admin/bundles"><i class="fa fa-tags" aria-hidden="true">&nbsp;</i> Bundles</a>
                      <ul class="dropdown-menu">
                        <li>
                          <a href="<%= new_admin_bundle_path() %>"><i class="fa fa-plus" aria-hidden="true">&nbsp;</i> New Bundle</a>
                        </li>
                      </ul>
                    </li>
                    <li class="<%= 'active' if controller?('admin/products') %>">
                      <a href="/admin/products"><i class="fa fa-cubes" aria-hidden="true">&nbsp;</i> Products</a>
                      <ul class="dropdown-menu">
                        <li>
                          <a href="<%= new_admin_product_path(type: :film) %>"><i class="fa fa-plus" aria-hidden="true">&nbsp;</i> New Film</a>
                        </li>
                        <li>
                          <a href="<%= new_admin_product_path(type: :music) %>"><i class="fa fa-plus" aria-hidden="true">&nbsp;</i> New Music</a>
                        </li>
                        <li>
                          <a href="<%= new_admin_product_path(type: :game) %>"><i class="fa fa-plus" aria-hidden="true">&nbsp;</i> New Game</a>
                        </li>
                      </ul>
                    </li>
                  </ul>
                </div>
              </div>
            </nav>
          </div>
          <div class="col-sm-9 col-lg-10 main-container">
            <%= yield %>
          </div>
          </div>
      </div>
   </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
   <head>
      <title>EntMe</title>
      <%= csrf_meta_tags %>
      <%= stylesheet_link_tag    'application', media: 'all' %>
      <%= javascript_include_tag 'application' %>

      <%= yield :head %>
   </head>
   <body cz-shortcut-listen="true">
      <main id="page-content" class="wrap container">
         <!-- Nav bar header -->
         <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container">
               <div class="navbar-header">
                  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  </button>
                  <a class="navbar-brand" href=<%=root_path%> ><i class="fa fa-cube"></i> Ent-Me!</a>
               </div>
               <div class="navbar-right navbar-utils">
                  <ul class="list-unstyled clearfix">
                    <%if user_signed_in? %>
                       <li class="hidden-xs">
                          <%if current_user.admin%>
                            <%=link_to "Admin", "/admin", class: "btn"%>
                          <%end%>
                          <%=link_to "Sign out", destroy_user_session_path, method: "DELETE", class: "btn"%>
                       </li>
                    <%else%>
                      <% if controller_name != 'sessions' %>
                       <li class="hidden-xs">
                          <a href=<%=new_user_session_path%> class="btn"><span>sign in</span></a>
                       </li>
                      <%end%>

                      <% if controller_name != 'registrations' %>
                       <li class="hidden-xs">
                          <a href=<%=new_user_registration_path%> class="btn"><span>sign up</span></a>
                       </li>
                       <%end%>
                    <%end%>


                     <li id="navbar-totals" class="totals">
                        <span class="hidden-xs js-item-count">0 Items</span>
                        <span class="visible-lg js-total-price">$0</span>
                        <span class="visible-xs item-number">0</span>
                     </li>



                     <li class="dropdown js-cart-dropdown">
                        <a href="shop.html" data-toggle="dropdown" class="btn btn-primary cart-btn">
                        <i class="fa fa-shopping-cart"></i>
                        </a>
                        <div id="mini-cart" class="dropdown-menu">
                           <ul class="cart-items list-unstyled hidden-xs">
                           </ul>
                           <div class="mini-cart-totals">
                              <h4 class="subtotal js-subtotal">Subtotal: $0.00</h4>
                              <a class="btn btn-default btn-lg" href=<%=carts_path%> >View Cart</a>
                              <a class="col-xs-12 btn btn-danger solid btn-lg" href=<%=checkout_index_path%> >Checkout</a>
                           </div>
                        </div>
                     </li>
                  </ul>
               </div>
               <div class="navbar-collapse collapse">
                  <div class="navbar-left">
                     <ul id="main-nav" class="nav navbar-nav">
                        <% Product::TYPES.each do |type| %>
                          <li class="dropdown <%='active' if @type == type.pluralize%>">
                             <a href=<%=type_products_path(type.pluralize)%>>
                              <%=type.pluralize%>
                             </a>
                          </li>
                        <%end%>

                        <li class="dropdown <%='active' if controller_name == 'news'%>" style="margin-left: 45px;">
                          <a href=<%=news_index_path%>>
                            News
                          </a>
                        </li>
                        <li class="visible-xs col-xs-12">
                           <a href="shop.html" class="btn btn-default">Login <i class="fa fa-lock"></i></a>
                        </li>
                     </ul>
                  </div>
                  <form id="search-form" class="navbar-form" role="form" method="get" action=<%=search_products_path%>>
                     <div class="input-group" style="width:100%">
                        <input type="text" class="search-form form-control" name="keyward" id="query" placeholder="Type your search term and press Enter" autocomplete="off" value=<%=@search%>>
                        <span class="input-group-btn" style="width: 10px;">
                        <button class="btn search-btn toggle hidden-xs hidden-sm" type="button"><i class="fa fa-search"></i></button>
                        <button class="btn search-btn hidden-md hidden-lg" type="submit"><i class="fa fa-search"></i></button>
                        </span>
                     </div>
                     <!-- /input-group -->
                  </form>
               </div>
               <!--/.navbar-collapse -->
            </div>
         </nav>
         <!-- end Nav bar header -->
       <%if notice%>
        <p class="notice"><%= notice %></p>
       <%end%>
       <%if alert%>
        <p class="alert"><%= alert %></p>
       <%end%>

         <%= yield %>

      </main>
      <div class="container padding0">
        <footer id="page-footer">
          <div id="fb-root"></div>

           <div class="container">
              <div class="footer-contact text-center row">
                 <div class="col-xs-12 col-sm-4 col-lg-2">
                    <a href="javascript:;"><i class="fa fa-envelope-o"></i>info@rubikal.com</a>
                 </div>
                 <div class="col-xs-12 col-sm-4 col-lg-2">
                    <a href="javascript:;"><i class="fa fa-phone"></i>+2 (0100) 2715-360</a>
                 </div>
                 <div class="social-buttons col-xs-12 col-sm-4 col-lg-2">
                    <a class="facebook" href="javascript:;"><i class="fa fa-facebook"></i></a>
                    <a class="twitter" href="javascript:;"><i class="fa fa-twitter"></i></a>
                    <a class="gplus" href="javascript:;"><i class="fa fa-google-plus"></i></a>
                 </div>
              </div>
              <div class="footer-info wrap row">
                 <div class="col-sm-6">
                    <ul class="list-unstyled">
                       <li>&copy; Rubikal! 2017</li>
                       <li><a href=<%=about_path%>>About</a></li>
                    </ul>
                 </div>
                 <div class="col-sm-6">
                    <p class="love">Made with <i class="glyphicon glyphicon-heart-empty"></i> Rubikal</p>
                 </div>
              </div>
           </div>
        </footer>
      </div>
   </body>
</html>